name: Build, Tag, and Deploy to Minikube

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build-tag-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: |
          echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Create Git tag
        id: tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Set patch to new version
        id: set_patch_version
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version patch -m ":bookmark: new version %s"
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Minikube
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" > ~/.kube/config
          kubectl apply -f kubernetes/deployment.yaml